"""cert info table in  database migration

Revision ID: 039468fd1459
Revises: c0849a777082
Create Date: 2021-08-03 23:26:17.609031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039468fd1459'
down_revision = 'c0849a777082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates_info',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=50), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('file_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificates_info')
    # ### end Alembic commands ###
