"""user info table added!

Revision ID: 21071863d330
Revises: 940fa7471ca0
Create Date: 2022-01-09 00:08:25.484114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21071863d330'
down_revision = '940fa7471ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=25), nullable=False),
    sa.Column('user_password', sa.String(length=50), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('user_info')
    # ### end Alembic commands ###
