"""db info table added


Revision ID: 8784d98db364
Revises: e9d444ac9f55
Create Date: 2021-09-02 23:43:11.178951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8784d98db364'
down_revision = 'e9d444ac9f55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_connection_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('db_name', sa.String(length=50), nullable=False),
    sa.Column('db_connection_string', sa.String(length=250), nullable=True),
    sa.Column('db_user_name', sa.String(length=120), nullable=True),
    sa.Column('db_password', sa.String(length=250), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('db_name')
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_table('db_connection_info')
    # ### end Alembic commands ###
