"""Certificate table updated

Revision ID: e9d444ac9f55
Revises: 039468fd1459
Create Date: 2021-08-16 00:24:30.676517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d444ac9f55'
down_revision = '039468fd1459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates_info', sa.Column('file_password', sa.String(length=120), nullable=True))
    op.alter_column('queue_config', 'config_value',
               nullable=None)
    #existing_type=sa.VARCHAR(length=120),
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('queue_config', 'config_value',
               nullable=False)
    #existing_type=sa.VARCHAR(length=120),

    op.drop_column('certificates_info', 'file_password')
    # ### end Alembic commands ###
